### ISSUE TITLE
About animation after tracking optimized

### ISSUE THREAD

**Issue by Dratlan** [philgras/video-head-tracker#5] opened 2022-07-01 10:54 UTC
Can you help me to figure out the problem of animation? the log information is below:

[07/01 16:48:55 vht.model.tracking]: Finished optimization. Saving results ...
[07/01 16:48:55 vht.model.tracking]: Started Animation
MovieWriter stderr:
[libopenh264 @ 0x55cd4622e2c0] Incorrect library version loaded
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

Saving frame 0 of 1496
Saving frame 1 of 1496
Traceback (most recent call last):
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 236, in saving
    yield self
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 1095, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 353, in grab_frame
    self.fig.savefig(self._proc.stdin, format=self.frame_format,
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 412, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 486, in print_raw
    fh.write(renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/psdz/headavater/neuralhead/avatars/deps/video-head-tracker/vht/optimize_tracking.py", line 49, in <module>
    main()
  File "/home/psdz/headavater/neuralhead/avatars/deps/video-head-tracker/vht/optimize_tracking.py", line 45, in main
    tracker.optimize()
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/vht/model/tracking.py", line 335, in optimize
    self._export_result(make_visualization=True)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/vht/model/tracking.py", line 1176, in _export_result
    self._save_tracking_animation(self._out_dir / "tracking_visual.mp4")
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/vht/model/tracking.py", line 1105, in _save_tracking_animation
    anim.save(outpath, progress_callback=callback)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 1095, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 238, in saving
    self.finish()
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 344, in finish
    self._cleanup()  # Inline _cleanup() once cleanup() is removed.
  File "/home/psdz/miniconda3/envs/headavater/lib/python3.9/site-packages/matplotlib/animation.py", line 375, in _cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '2000x400', '-pix_fmt', 'rgba', '-r', '29.999999999999996', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', PosixPath('/home/psdz/headavater/neuralhead/avatars/result/tracking_0/tracking_visual.mp4')]' returned non-zero exit status 1.

**Comment by philgras** [comment] 2022-07-15 09:32
Hi,

I think the error is printed in the first few lines:
```
MovieWriter stderr:
[libopenh264 @ 0x55cd4622e2c0] Incorrect library version loaded
Error initializing output stream 0:0
```
So, there seems to be a version issue with libopenh264 for video encoding. If you search for that error message online, you will probably find some starting points. For me, it is hard to reproduce.

Please consider closing the issue if you managed to solve it.

**Closed as completed** 2022-07-15 09:35 UTC

**Comment by Dratlan** [comment] 2022-07-15 09:36
Thanks for your reply, I've now already closed it.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月15日(星期五) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [philgras/video-head-tracker] About animation after tracking optimized (Issue #5)





 
Hi,
 
I think the error is printed in the first few lines:
 MovieWriter stderr: [libopenh264 @ 0x55cd4622e2c0] Incorrect library version loaded Error initializing output stream 0:0  
So, there seems to be a version issue with libopenh264 for video encoding. If you search for that error message online, you will probably find some starting points. For me, it is hard to reproduce.
 
Please consider closing the issue if you managed to solve it.

**Comment by liushengtong-nreal** [comment] 2022-07-25 09:41
> Hi,
> 
> I think the error is printed in the first few lines:
> 
> ```
> MovieWriter stderr:
> [libopenh264 @ 0x55cd4622e2c0] Incorrect library version loaded
> Error initializing output stream 0:0
> ```
> 
> So, there seems to be a version issue with libopenh264 for video encoding. If you search for that error message online, you will probably find some starting points. For me, it is hard to reproduce.
> 
> Please consider closing the issue if you managed to solve it.

hell

> Thanks for your reply, I've now already closed it.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月15日(星期五) 下午5:32 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [philgras/video-head-tracker] About animation after tracking optimized (Issue #5) Hi, I think the error is printed in the first few lines: MovieWriter stderr: [libopenh264 @ 0x55cd4622e2c0] Incorrect library version loaded Error initializing output stream 0:0 So, there seems to be a version issue with libopenh264 for video encoding. If you search for that error message online, you will probably find some starting points. For me, it is hard to reproduce. Please consider closing the issue if you managed to solve it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

hello, I meet the same error, and I cannot find a correct way, can you tell me how to deal with the issue? thank you very much.

**Comment by yangqing-yq** [comment] 2022-08-20 11:50
same issue here. 
how to solve?
